/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.novedadessary.Views;

/**
 *
 * @author Misae
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        PanelInicio.setVisible(true);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuLateral = new javax.swing.JPanel();
        btnMenuControlVentas = new javax.swing.JLabel();
        btnMenuCatalogos = new javax.swing.JLabel();
        btnMenuInventarios = new javax.swing.JLabel();
        btnMenuEmpleados = new javax.swing.JLabel();
        btnMenuVehiculos = new javax.swing.JLabel();
        btnMenuBodegas = new javax.swing.JLabel();
        btnMenuControlSistema = new javax.swing.JLabel();
        btnMenuUtilerias = new javax.swing.JLabel();
        btnMenuInicio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        btnCapturarAbono = new javax.swing.JButton();
        btnDescuento = new javax.swing.JButton();
        btnCuentasAtrasadas = new javax.swing.JButton();
        btnConsultaSaldo = new javax.swing.JButton();
        btnNuevaVenta = new javax.swing.JButton();
        btnNuevoCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnSettings = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        PanelControlCatalogos = new javax.swing.JPanel();
        Header1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnSettings1 = new javax.swing.JButton();
        btnCrearCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        PanelControlVentas = new javax.swing.JPanel();
        Header2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnSettings2 = new javax.swing.JButton();
        PanelControlInventario = new javax.swing.JPanel();
        Header3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        btnSettings3 = new javax.swing.JButton();
        PanelControlEmpleados = new javax.swing.JPanel();
        Header4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnSettings4 = new javax.swing.JButton();
        PanelControlVehiculos = new javax.swing.JPanel();
        Header5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnSettings5 = new javax.swing.JButton();
        PanelControlBodegas = new javax.swing.JPanel();
        Header6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnSettings6 = new javax.swing.JButton();
        PanelControlSistema = new javax.swing.JPanel();
        Header7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnSettings7 = new javax.swing.JButton();
        PanelUtilerias = new javax.swing.JPanel();
        Header8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnSettings8 = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Novedades Sary | Sistema Principal");
        setBackground(new java.awt.Color(250, 247, 242));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuLateral.setBackground(new java.awt.Color(53, 53, 53));

        btnMenuControlVentas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuControlVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuControlVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shopping-cart.png"))); // NOI18N
        btnMenuControlVentas.setText(" Control de ventas");
        btnMenuControlVentas.setToolTipText("");
        btnMenuControlVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuControlVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuControlVentasMouseClicked(evt);
            }
        });

        btnMenuCatalogos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuCatalogos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuCatalogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/align-left.png"))); // NOI18N
        btnMenuCatalogos.setText(" Control de catalogo");
        btnMenuCatalogos.setToolTipText("");
        btnMenuCatalogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuCatalogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuCatalogosMouseClicked(evt);
            }
        });

        btnMenuInventarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuInventarios.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        btnMenuInventarios.setText("Control de inventarios");
        btnMenuInventarios.setToolTipText("");
        btnMenuInventarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuInventariosMouseClicked(evt);
            }
        });

        btnMenuEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee.png"))); // NOI18N
        btnMenuEmpleados.setText(" Control de empleados");
        btnMenuEmpleados.setToolTipText("");
        btnMenuEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuEmpleadosMouseClicked(evt);
            }
        });

        btnMenuVehiculos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delivery-truck.png"))); // NOI18N
        btnMenuVehiculos.setText(" Control de vehículos");
        btnMenuVehiculos.setToolTipText("");
        btnMenuVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuVehiculosMouseClicked(evt);
            }
        });

        btnMenuBodegas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuBodegas.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuBodegas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box.png"))); // NOI18N
        btnMenuBodegas.setText(" Control de bodegas");
        btnMenuBodegas.setToolTipText("");
        btnMenuBodegas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuBodegas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuBodegasMouseClicked(evt);
            }
        });

        btnMenuControlSistema.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuControlSistema.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuControlSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bar-chart.png"))); // NOI18N
        btnMenuControlSistema.setText(" Control del sistema");
        btnMenuControlSistema.setToolTipText("");
        btnMenuControlSistema.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuControlSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuControlSistemaMouseClicked(evt);
            }
        });

        btnMenuUtilerias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuUtilerias.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuUtilerias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gear.png"))); // NOI18N
        btnMenuUtilerias.setText(" Utilerías");
        btnMenuUtilerias.setToolTipText("");
        btnMenuUtilerias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUtilerias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuUtileriasMouseClicked(evt);
            }
        });

        btnMenuInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenuInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu-button.png"))); // NOI18N
        btnMenuInicio.setText(" Inicio");
        btnMenuInicio.setToolTipText("");
        btnMenuInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuInicioMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-white.png"))); // NOI18N
        jLabel2.setText("Usuario");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(98, 102, 93));
        jLabel13.setText("OPERACIÓN");
        jLabel13.setToolTipText("");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(98, 102, 93));
        jLabel16.setText("SISTEMA");
        jLabel16.setToolTipText("");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(98, 102, 93));
        jLabel17.setText("ADMINISTRACIÓN");
        jLabel17.setToolTipText("");

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2))
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuInventarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuControlVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuCatalogos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuBodegas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuControlSistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuUtilerias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuInicio)
                .addGap(18, 18, 18)
                .addComponent(btnMenuCatalogos)
                .addGap(18, 18, 18)
                .addComponent(btnMenuControlVentas)
                .addGap(18, 18, 18)
                .addComponent(btnMenuInventarios)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuEmpleados)
                .addGap(18, 18, 18)
                .addComponent(btnMenuVehiculos)
                .addGap(18, 18, 18)
                .addComponent(btnMenuBodegas)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuControlSistema)
                .addGap(18, 18, 18)
                .addComponent(btnMenuUtilerias)
                .addGap(83, 83, 83))
        );

        getContentPane().add(MenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 570));

        PanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelInicio.setEnabled(false);

        btnCapturarAbono.setBackground(new java.awt.Color(21, 101, 192));
        btnCapturarAbono.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCapturarAbono.setForeground(new java.awt.Color(255, 255, 255));
        btnCapturarAbono.setText("Capturar Abono");
        btnCapturarAbono.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapturarAbono.addActionListener(this::btnCapturarAbonoActionPerformed);

        btnDescuento.setBackground(new java.awt.Color(106, 27, 154));
        btnDescuento.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnDescuento.setForeground(new java.awt.Color(255, 255, 255));
        btnDescuento.setText("Descuento");
        btnDescuento.addActionListener(this::btnDescuentoActionPerformed);

        btnCuentasAtrasadas.setBackground(new java.awt.Color(198, 40, 40));
        btnCuentasAtrasadas.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnCuentasAtrasadas.setForeground(new java.awt.Color(255, 255, 255));
        btnCuentasAtrasadas.setText("Cuentas Atrasadas");
        btnCuentasAtrasadas.addActionListener(this::btnCuentasAtrasadasActionPerformed);

        btnConsultaSaldo.setBackground(new java.awt.Color(0, 131, 143));
        btnConsultaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnConsultaSaldo.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaSaldo.setText(" Consulta De Saldo");
        btnConsultaSaldo.addActionListener(this::btnConsultaSaldoActionPerformed);

        btnNuevaVenta.setBackground(new java.awt.Color(46, 125, 50));
        btnNuevaVenta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevaVenta.addActionListener(this::btnNuevaVentaActionPerformed);

        btnNuevoCliente.setBackground(new java.awt.Color(239, 108, 0));
        btnNuevoCliente.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo Cliente");
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Acciones rápidas:");

        Header.setBackground(new java.awt.Color(201, 166, 107));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Novedades Sary");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Sistema Principal");
        jLabel12.setToolTipText("");

        btnSettings.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings.addActionListener(this::btnSettingsActionPerformed);

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(22, 22, 22)))
                .addGap(344, 344, 344)
                .addComponent(btnSettings)
                .addGap(25, 25, 25))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-transparente.png"))); // NOI18N

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel15)
                        .addGroup(PanelInicioLayout.createSequentialGroup()
                            .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnNuevoCliente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCapturarAbono))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnConsultaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCuentasAtrasadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnConsultaSaldo))
                    .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNuevaVenta)
                        .addComponent(btnCapturarAbono)))
                .addGap(18, 18, 18)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevoCliente)
                    .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDescuento)
                        .addComponent(btnCuentasAtrasadas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        getContentPane().add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlCatalogos.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlCatalogos.setEnabled(false);

        Header1.setBackground(new java.awt.Color(201, 166, 107));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Novedades Sary");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("Control Catalogo");
        jLabel18.setToolTipText("");

        btnSettings1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings1.addActionListener(this::btnSettings1ActionPerformed);

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel3)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addGap(370, 370, 370)))
                .addComponent(btnSettings1)
                .addGap(25, 25, 25))
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addGroup(Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18))
                    .addGroup(Header1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnCrearCliente.setBackground(new java.awt.Color(21, 101, 192));
        btnCrearCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCliente.setText("Nuevo Cliente");
        btnCrearCliente.addActionListener(this::btnCrearClienteActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "F. U.VTA", "Cuenta", "Cliente", "Domicilio", "Teléfono", "Moroso", "Observaciones", "Acciones"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout PanelControlCatalogosLayout = new javax.swing.GroupLayout(PanelControlCatalogos);
        PanelControlCatalogos.setLayout(PanelControlCatalogosLayout);
        PanelControlCatalogosLayout.setHorizontalGroup(
            PanelControlCatalogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelControlCatalogosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelControlCatalogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(PanelControlCatalogosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCrearCliente)))
                .addGap(23, 23, 23))
        );
        PanelControlCatalogosLayout.setVerticalGroup(
            PanelControlCatalogosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlCatalogosLayout.createSequentialGroup()
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCrearCliente)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelControlCatalogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlVentas.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlVentas.setEnabled(false);

        Header2.setBackground(new java.awt.Color(201, 166, 107));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Novedades Sary");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Control Ventas");
        jLabel19.setToolTipText("");

        btnSettings2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings2.addActionListener(this::btnSettings2ActionPerformed);

        javax.swing.GroupLayout Header2Layout = new javax.swing.GroupLayout(Header2);
        Header2.setLayout(Header2Layout);
        Header2Layout.setHorizontalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGroup(Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header2Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel4)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)
                        .addGap(380, 380, 380)))
                .addComponent(btnSettings2)
                .addGap(25, 25, 25))
        );
        Header2Layout.setVerticalGroup(
            Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header2Layout.createSequentialGroup()
                .addGroup(Header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(Header2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlVentasLayout = new javax.swing.GroupLayout(PanelControlVentas);
        PanelControlVentas.setLayout(PanelControlVentasLayout);
        PanelControlVentasLayout.setHorizontalGroup(
            PanelControlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlVentasLayout.setVerticalGroup(
            PanelControlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlVentasLayout.createSequentialGroup()
                .addComponent(Header2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlInventario.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlInventario.setEnabled(false);

        Header3.setBackground(new java.awt.Color(201, 166, 107));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Novedades Sary");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Control Inventarios");
        jLabel20.setToolTipText("");

        btnSettings3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings3.addActionListener(this::btnSettings3ActionPerformed);

        javax.swing.GroupLayout Header3Layout = new javax.swing.GroupLayout(Header3);
        Header3.setLayout(Header3Layout);
        Header3Layout.setHorizontalGroup(
            Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header3Layout.createSequentialGroup()
                .addGroup(Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header3Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel5)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(358, 358, 358)))
                .addComponent(btnSettings3)
                .addGap(25, 25, 25))
        );
        Header3Layout.setVerticalGroup(
            Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header3Layout.createSequentialGroup()
                .addGroup(Header3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addGroup(Header3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings3)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlInventarioLayout = new javax.swing.GroupLayout(PanelControlInventario);
        PanelControlInventario.setLayout(PanelControlInventarioLayout);
        PanelControlInventarioLayout.setHorizontalGroup(
            PanelControlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlInventarioLayout.setVerticalGroup(
            PanelControlInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlInventarioLayout.createSequentialGroup()
                .addComponent(Header3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlEmpleados.setEnabled(false);

        Header4.setBackground(new java.awt.Color(201, 166, 107));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Novedades Sary");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("Control Empleados");
        jLabel21.setToolTipText("");

        btnSettings4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings4.addActionListener(this::btnSettings4ActionPerformed);

        javax.swing.GroupLayout Header4Layout = new javax.swing.GroupLayout(Header4);
        Header4.setLayout(Header4Layout);
        Header4Layout.setHorizontalGroup(
            Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header4Layout.createSequentialGroup()
                .addGroup(Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header4Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel6)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)
                        .addGap(358, 358, 358)))
                .addComponent(btnSettings4)
                .addGap(25, 25, 25))
        );
        Header4Layout.setVerticalGroup(
            Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header4Layout.createSequentialGroup()
                .addGroup(Header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21))
                    .addGroup(Header4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings4)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlEmpleadosLayout = new javax.swing.GroupLayout(PanelControlEmpleados);
        PanelControlEmpleados.setLayout(PanelControlEmpleadosLayout);
        PanelControlEmpleadosLayout.setHorizontalGroup(
            PanelControlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlEmpleadosLayout.setVerticalGroup(
            PanelControlEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlEmpleadosLayout.createSequentialGroup()
                .addComponent(Header4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlVehiculos.setEnabled(false);

        Header5.setBackground(new java.awt.Color(201, 166, 107));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("Novedades Sary");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Control Vehículos");
        jLabel22.setToolTipText("");

        btnSettings5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings5.addActionListener(this::btnSettings5ActionPerformed);

        javax.swing.GroupLayout Header5Layout = new javax.swing.GroupLayout(Header5);
        Header5.setLayout(Header5Layout);
        Header5Layout.setHorizontalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header5Layout.createSequentialGroup()
                .addGroup(Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header5Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel7)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel22)
                        .addGap(366, 366, 366)))
                .addComponent(btnSettings5)
                .addGap(25, 25, 25))
        );
        Header5Layout.setVerticalGroup(
            Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header5Layout.createSequentialGroup()
                .addGroup(Header5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(Header5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings5)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlVehiculosLayout = new javax.swing.GroupLayout(PanelControlVehiculos);
        PanelControlVehiculos.setLayout(PanelControlVehiculosLayout);
        PanelControlVehiculosLayout.setHorizontalGroup(
            PanelControlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlVehiculosLayout.setVerticalGroup(
            PanelControlVehiculosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlVehiculosLayout.createSequentialGroup()
                .addComponent(Header5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlBodegas.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlBodegas.setEnabled(false);

        Header6.setBackground(new java.awt.Color(201, 166, 107));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Novedades Sary");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Control Bodegas");
        jLabel23.setToolTipText("");

        btnSettings6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings6.addActionListener(this::btnSettings6ActionPerformed);

        javax.swing.GroupLayout Header6Layout = new javax.swing.GroupLayout(Header6);
        Header6.setLayout(Header6Layout);
        Header6Layout.setHorizontalGroup(
            Header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header6Layout.createSequentialGroup()
                .addGroup(Header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header6Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel8)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)
                        .addGap(366, 366, 366)))
                .addComponent(btnSettings6)
                .addGap(25, 25, 25))
        );
        Header6Layout.setVerticalGroup(
            Header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header6Layout.createSequentialGroup()
                .addGroup(Header6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23))
                    .addGroup(Header6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings6)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlBodegasLayout = new javax.swing.GroupLayout(PanelControlBodegas);
        PanelControlBodegas.setLayout(PanelControlBodegasLayout);
        PanelControlBodegasLayout.setHorizontalGroup(
            PanelControlBodegasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlBodegasLayout.setVerticalGroup(
            PanelControlBodegasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlBodegasLayout.createSequentialGroup()
                .addComponent(Header6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlBodegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelControlSistema.setBackground(new java.awt.Color(255, 255, 255));
        PanelControlSistema.setEnabled(false);

        Header7.setBackground(new java.awt.Color(201, 166, 107));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("Novedades Sary");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("Control Sistema");
        jLabel24.setToolTipText("");

        btnSettings7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings7.addActionListener(this::btnSettings7ActionPerformed);

        javax.swing.GroupLayout Header7Layout = new javax.swing.GroupLayout(Header7);
        Header7.setLayout(Header7Layout);
        Header7Layout.setHorizontalGroup(
            Header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header7Layout.createSequentialGroup()
                .addGroup(Header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header7Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel9)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24)
                        .addGap(371, 371, 371)))
                .addComponent(btnSettings7)
                .addGap(25, 25, 25))
        );
        Header7Layout.setVerticalGroup(
            Header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header7Layout.createSequentialGroup()
                .addGroup(Header7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24))
                    .addGroup(Header7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings7)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelControlSistemaLayout = new javax.swing.GroupLayout(PanelControlSistema);
        PanelControlSistema.setLayout(PanelControlSistemaLayout);
        PanelControlSistemaLayout.setHorizontalGroup(
            PanelControlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelControlSistemaLayout.setVerticalGroup(
            PanelControlSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelControlSistemaLayout.createSequentialGroup()
                .addComponent(Header7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelControlSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        PanelUtilerias.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtilerias.setEnabled(false);

        Header8.setBackground(new java.awt.Color(201, 166, 107));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("Novedades Sary");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Control Utilerías");
        jLabel25.setToolTipText("");

        btnSettings8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSettings8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings.png"))); // NOI18N
        btnSettings8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSettings8.addActionListener(this::btnSettings8ActionPerformed);

        javax.swing.GroupLayout Header8Layout = new javax.swing.GroupLayout(Header8);
        Header8.setLayout(Header8Layout);
        Header8Layout.setHorizontalGroup(
            Header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header8Layout.createSequentialGroup()
                .addGroup(Header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header8Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel10)
                        .addGap(344, 344, 344))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Header8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)
                        .addGap(372, 372, 372)))
                .addComponent(btnSettings8)
                .addGap(25, 25, 25))
        );
        Header8Layout.setVerticalGroup(
            Header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header8Layout.createSequentialGroup()
                .addGroup(Header8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Header8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25))
                    .addGroup(Header8Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnSettings8)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelUtileriasLayout = new javax.swing.GroupLayout(PanelUtilerias);
        PanelUtilerias.setLayout(PanelUtileriasLayout);
        PanelUtileriasLayout.setHorizontalGroup(
            PanelUtileriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelUtileriasLayout.setVerticalGroup(
            PanelUtileriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtileriasLayout.createSequentialGroup()
                .addComponent(Header8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );

        getContentPane().add(PanelUtilerias, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 970, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        // TODO add your handling code here:
        Settings objSettings = new Settings();
        objSettings.setLocationRelativeTo(null);
        objSettings.setVisible(true);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void btnMenuCatalogosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuCatalogosMouseClicked
        // Este es el botón de catalogos en el menu
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(true);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuCatalogosMouseClicked

    private void btnMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuInicioMouseClicked
        // Este es el botón de inicio en el menu
        PanelInicio.setVisible(true);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuInicioMouseClicked

    private void btnSettings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings1ActionPerformed
        // TODO add your handling code here:
        Settings objSettings = new Settings();
        objSettings.setLocationRelativeTo(null);
        objSettings.setVisible(true);
    }//GEN-LAST:event_btnSettings1ActionPerformed

    private void btnSettings2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings2ActionPerformed

    private void btnMenuControlVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuControlVentasMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(true);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuControlVentasMouseClicked

    private void btnSettings3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings3ActionPerformed

    private void btnMenuInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuInventariosMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(true);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuInventariosMouseClicked

    private void btnSettings4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings4ActionPerformed

    private void btnMenuEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuEmpleadosMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(true);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuEmpleadosMouseClicked

    private void btnSettings5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings5ActionPerformed

    private void btnMenuVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuVehiculosMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(true);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuVehiculosMouseClicked

    private void btnSettings6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings6ActionPerformed

    private void btnMenuBodegasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuBodegasMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(true);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuBodegasMouseClicked

    private void btnSettings7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings7ActionPerformed

    private void btnMenuControlSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuControlSistemaMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(true);
        PanelUtilerias.setVisible(false);
    }//GEN-LAST:event_btnMenuControlSistemaMouseClicked

    private void btnSettings8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettings8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettings8ActionPerformed

    private void btnMenuUtileriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUtileriasMouseClicked
        // TODO add your handling code here:
        PanelInicio.setVisible(false);
        PanelControlCatalogos.setVisible(false);
        PanelControlVentas.setVisible(false);
        PanelControlInventario.setVisible(false);
        PanelControlEmpleados.setVisible(false);
        PanelControlVehiculos.setVisible(false);
        PanelControlBodegas.setVisible(false);
        PanelControlSistema.setVisible(false);
        PanelUtilerias.setVisible(true);
    }//GEN-LAST:event_btnMenuUtileriasMouseClicked

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:
        NuevaVenta objNuevaVenta = new NuevaVenta();
        objNuevaVenta.setLocationRelativeTo(null);
        objNuevaVenta.setVisible(true);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnCapturarAbonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarAbonoActionPerformed
        // TODO add your handling code here:
        CapturarAbono objCapturarAbono = new CapturarAbono();
        objCapturarAbono.setLocationRelativeTo(null);
        objCapturarAbono.setVisible(true);
    }//GEN-LAST:event_btnCapturarAbonoActionPerformed

    private void btnConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaSaldoActionPerformed
        // TODO add your handling code here:
        ConsultaSaldo objConsultaSaldo = new ConsultaSaldo();
        objConsultaSaldo.setLocationRelativeTo(null);
        objConsultaSaldo.setVisible(true);
    }//GEN-LAST:event_btnConsultaSaldoActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        // TODO add your handling code here:
        NuevoCliente objNuevoCliente = new NuevoCliente();
        objNuevoCliente.setLocationRelativeTo(null);
        objNuevoCliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void btnDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescuentoActionPerformed
        // TODO add your handling code here:
        Descuento objDescuento = new Descuento();
        objDescuento.setLocationRelativeTo(null);
        objDescuento.setVisible(true);
    }//GEN-LAST:event_btnDescuentoActionPerformed

    private void btnCuentasAtrasadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasAtrasadasActionPerformed
        // TODO add your handling code here:
        CuentasAtrasadas objCuentasAtrasadas = new CuentasAtrasadas();
        objCuentasAtrasadas.setLocationRelativeTo(null);
        objCuentasAtrasadas.setVisible(true);
    }//GEN-LAST:event_btnCuentasAtrasadasActionPerformed

    private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
        // TODO add your handling code here:
        NuevoCliente objNuevoCliente = new NuevoCliente();
        objNuevoCliente.setLocationRelativeTo(null);
        objNuevoCliente.setVisible(true);
    }//GEN-LAST:event_btnCrearClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Header1;
    private javax.swing.JPanel Header2;
    private javax.swing.JPanel Header3;
    private javax.swing.JPanel Header4;
    private javax.swing.JPanel Header5;
    private javax.swing.JPanel Header6;
    private javax.swing.JPanel Header7;
    private javax.swing.JPanel Header8;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel PanelControlBodegas;
    private javax.swing.JPanel PanelControlCatalogos;
    private javax.swing.JPanel PanelControlEmpleados;
    private javax.swing.JPanel PanelControlInventario;
    private javax.swing.JPanel PanelControlSistema;
    private javax.swing.JPanel PanelControlVehiculos;
    private javax.swing.JPanel PanelControlVentas;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelUtilerias;
    private javax.swing.JButton btnCapturarAbono;
    private javax.swing.JButton btnConsultaSaldo;
    private javax.swing.JButton btnCrearCliente;
    private javax.swing.JButton btnCuentasAtrasadas;
    private javax.swing.JButton btnDescuento;
    private javax.swing.JLabel btnMenuBodegas;
    private javax.swing.JLabel btnMenuCatalogos;
    private javax.swing.JLabel btnMenuControlSistema;
    private javax.swing.JLabel btnMenuControlVentas;
    private javax.swing.JLabel btnMenuEmpleados;
    private javax.swing.JLabel btnMenuInicio;
    private javax.swing.JLabel btnMenuInventarios;
    private javax.swing.JLabel btnMenuUtilerias;
    private javax.swing.JLabel btnMenuVehiculos;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnSettings1;
    private javax.swing.JButton btnSettings2;
    private javax.swing.JButton btnSettings3;
    private javax.swing.JButton btnSettings4;
    private javax.swing.JButton btnSettings5;
    private javax.swing.JButton btnSettings6;
    private javax.swing.JButton btnSettings7;
    private javax.swing.JButton btnSettings8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
